### ISSUE TITLE
How to directly replace colorthief

### ISSUE THREAD

**Issue by konrad51** [bedapisl/fast-colorthief#10]
How would I directly replace the older colorthief .py ?

**Comment by bedapisl** [comment]
`pip3 uninstall fast-colorthief` should work.

**Comment by konrad51** [comment]
Sorry , I wasn't clear. I was wanting to replace colorthief.py in another program with fast-colorthief.py (other program is wizscreen by coolmule0). ...hopefully without changing original code of wizscreen . I am having a problem with white color overwhelming other colors in wizscreen amd was hoping fast-colorthief would be quicker and better. Thanks

**Comment by bedapisl** [comment]
I understand now. I don't think it is possible without changing the code of `wizscreen`. You would have to change at least the import (https://github.com/coolmule0/wizscreen/blob/master/wizscreen.py#L13) and how is the method called (https://github.com/coolmule0/wizscreen/blob/master/wizscreen.py#L70).
