### ISSUE TITLE
Move from `pybind` to `hpy`

### ISSUE THREAD

**Issue by baseplate-admin** [bedapisl/fast-colorthief#12]
Hi,

Would you be willing to move to [`hpy`](https://hpyproject.org) for better compatibility with pypy?

**Comment by bedapisl** [comment]
Hi, not in the near future, because it seems like a lot of work. Sorry for that.

**Comment by baseplate-admin** [comment]
Hi,

Could we discuss about this ?

Would you be willing to accept a PR if i added the changes?

**Comment by bedapisl** [comment]
Sure we can discuss it. 

I am not sure `hpy` is the right direction for this project. Some reasons:
1. Pybind is more mature and popular compared to `hpy` (13k stars vs 1k stars, `hpy` is in `alpha`)
2. The code here is in C++, hpy is "API for extending Python in C"
3. Pybind11 supports Pypy ("Python 3.6+, and PyPy3 7.3 are supported with an implementation-agnostic interface"), so the compatibility shouldn't be a problem I think
